#! /bin/bash
LIST_MOD=( EFF GDP RGDP King GKing OGKing )
LIST_EXT=( Seg )
# LIST_EXT=( Ctr Ell Seg)
CUT=33
for EXT in ${LIST_EXT[*]}
do
	for MOD in ${LIST_MOD[*]}
		do
		python3 runSpatial.py $MOD $CUT $EXT &
		# echo $MOD,$CUT,$EXT
		sleep 1
	done
done
